### ISSUE TITLE
[BUG] Opening Models with correctly modelled TimeSeries

### ISSUE THREAD

**Issue by LukasHeimann** [OpenManufacturingPlatform/sds-aspect-model-editor#9]
**Describe the bug**
I try to model time series data in my BAMM model. The editor supports me insofar, as I can create characteristic of type `bamm-c:TimeSeries`. Besides that, no more support is given. Validations pass fine even though this is not sufficient to model a time series in BAMM (I think about opening a bug for this at the BAMM SDK repository (https://github.com/OpenManufacturingPlatform/sds-sdk/issues/194)).

After a while, I found the relevant BAMM documentation and modelled my aspect accordingly: https://openmanufacturingplatform.github.io/sds-bamm-aspect-meta-model/bamm-specification/v1.0.0/modeling-guidelines.html#declaring-time-series

The BAMM CLI still validates my model successfully, the editor however gives only an error message: `Error on loading the aspect model -- Instantiator cannot load model!`.

I guess this is not supported as a consequence of the two limitations listed under https://github.com/OpenManufacturingPlatform/sds-aspect-model-editor/blob/ecb7047a13cabc0e14c4fdb2f3eb3e513d62718d/documentation/ame-guide/modules/ROOT/pages/known-limitations.adoc#current-limitations-related-to-the-bamm-aspect-meta-model, but it would be nice to have time series explicitly mentioned there as well.

Is there a roadmap for when those limitations will be fixed? I understand that BAMM v2 changes a couple of things especially around refining properties and time series via abstract entities / properties. Are you planning to not support BAMM v1 time series at all, and integrate time series support in your BAMM v2 support?

Also, the error message at the UI is not very helpful in conveying that the issue is related to the unsupported time series.

Thank you for your support!
Kind regards
Lukas

**Where**
Loading a model with a properly modeled `bamm-c:TimeSeries`.

**Comment by chris-volk** [comment]
Dear @LukasHeimann , thanks a lot for opening this issue and explaining as well as mentioning the related issue.
The correct usage of TimeSeries is indeed not possible with 4.0.0. 
https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/pull/142 
BAMM 2.0.0 indeed replaces refinement by abstract, see https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/releases https://github.com/OpenManufacturingPlatform/sds-bamm-aspect-meta-model/pull/142 "Evolve bamm:extends into bamm:refines-replacement" which - as you correctly point out - affects TimeSeries.

The contributors of AME intend to provide a newer version 4.1.0 with BAMM 2.0.0 support later this summer (end of August / September). Unless urgently required, fixing this bug in a bugfix version is not planned.
As soon as BAMM 2.0.0 is supported this will not be required anymore since the tool chain supports to auto-migrate underlying BAMM versions to the most up to date. (Feel free to let us know should this not be suitable for your use case.)

Let us keep this bug open until a newer version (or currently less likely bugfix workaround or actual bugfix release) is available.

**Comment by michelu89** [comment]
#18 BAMM 2.0.0 is now supported
